# set_mode:
#   name: Set Mode
#   description: Set Mode to Awake/Sleep/None
#   target:
#     entity:
#       domain: sensor
#       integration: glowdreaming
#   fields:
#     mode:
#       name: Mode
#       description: Mode
#       required: true
#       selector:
#         select:
#           options:
#             - Awake
#             - Sleep
#             - None
write_gatt:
  name: Write Data into Target UUID
  description: Write Data into Target UUID
  target:
    entity:
      domain: sensor
      integration: glowdreaming
  fields:
    target_uuid:
      name: Target UUID
      description: Target UUID
      required: true
      selector:
        text:
    data:
      name: Data
      description: Data
      required: true
      selector:
        text:
read_gatt:
  name: Read Data from Target UUID
  description: Read Data from Target UUID
  target:
    entity:
      domain: sensor
      integration: glowdreaming
  fields:
    target_uuid:
      name: Target UUID
      description: Target UUID
      required: true
      selector:
        text:
