set_mode:
  name: "Set Mode"
  description: "Set the mode of the device"
  target:
    entity:
      domain: sensor
      integration: glowdreaming
  fields:
    mode:
      name: "Mode"
      description: "Mode to set"
      required: true
      selector:
        select:
          options:
            - "off"
            - "noise_quiet"
            - "noise_medium"
            - "noise_loud"
write_gatt:
  name: Write Data into Target UUID
  description: Write Data into Target UUID
  target:
    entity:
      domain: sensor
      integration: glowdreaming
  fields:
    target_uuid:
      name: Target UUID
      description: Target UUID
      required: true
      selector:
        text:
    data:
      name: Data
      description: Data
      required: true
      selector:
        text:
read_gatt:
  name: Read Data from Target UUID
  description: Read Data from Target UUID
  target:
    entity:
      domain: sensor
      integration: glowdreaming
  fields:
    target_uuid:
      name: Target UUID
      description: Target UUID
      required: true
      selector:
        text:
