set_mode:
  name: Set Mode
  description: Set light effect, brightness and volume
  target:
    entity:
      domain: sensor
      integration: glowdreaming
  fields:
    light_effect:
      name: Light Effect
      description: Light Effect
      required: true
      selector:
        select:
          options:
            - Awake
            - Sleep
            - None
    brightness:
      name: Brightness
      description: Brightness
      required: true
      selector:
        select:
          options:
            - None
            - Low
            - Medium
            - High
    volume:
      name: Volume
      description: Volume
      required: true
      selector:
        select:
          options:
            - None
            - Low
            - Medium
            - High
set_sleep_brightness:
  name: Set Sleep Brightness
  description: Set brightness
  target:
    entity:
      domain: sensor
      integration: glowdreaming
  fields:
    brightness:
      name: Brightness
      description: Brightness
      required: true
      selector:
        select:
          options:
            - None
            - Low
            - Medium
            - High
set_awake_brightness:
  name: Set Awake Brightness
  description: Set brightness
  target:
    entity:
      domain: sensor
      integration: glowdreaming
  fields:
    brightness:
      name: Brightness
      description: Brightness
      required: true
      selector:
        select:
          options:
            - None
            - Low
            - Medium
            - High
set_volume:
  name: Set Volume
  description: Set volume
  target:
    entity:
      domain: sensor
      integration: glowdreaming
  fields:
    volume:
      name: Volume
      description: Volume
      required: true
      selector:
        select:
          options:
            - None
            - Low
            - Medium
            - High
write_gatt:
  name: Write Data into Target UUID
  description: Write Data into Target UUID
  target:
    entity:
      domain: sensor
      integration: glowdreaming
  fields:
    target_uuid:
      name: Target UUID
      description: Target UUID
      required: true
      selector:
        text:
    data:
      name: Data
      description: Data
      required: true
      selector:
        text:
read_gatt:
  name: Read Data from Target UUID
  description: Read Data from Target UUID
  target:
    entity:
      domain: sensor
      integration: glowdreaming
  fields:
    target_uuid:
      name: Target UUID
      description: Target UUID
      required: true
      selector:
        text:
